DROP TABLE IF EXISTS departments;
CREATE TABLE departments (DEPARTMENT_ID INT PRIMARY KEY, DEPARTMENT_NAME VARCHAR(255), DEPARTMENT_CODE VARCHAR(255));

INSERT INTO departments VALUES(2, 'DEPARTMENT B', 'DEPARTMENT CODE B');

INSERT INTO TEST VALUES(2, 'World');

SELECT * FROM departments ORDER BY DEPARTMENT_ID;

UPDATE departments SET DEPARTMENT_NAME='DEPARTMENT B' WHERE DEPARTMENT_ID=2;
SELECT * FROM departments ORDER BY DEPARTMENT_ID;

DELETE FROM departments WHERE ID=2;